/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradletest;

import org.junit.Test;
import static org.junit.Assert.*;

public class CalculatorTest {
    @Test public void calculatorAdd() {
        Calculator classUnderTest = new Calculator();
        assertEquals(2, classUnderTest.add(1, 1));
    }

    @Test public void calculatorSub() {
        Calculator classUnderTest = new Calculator();
        assertEquals(0, classUnderTest.sub(1, 1));
    }
}
