/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradletest;

public class Calculator {
    public int add(int a, int b) {
        return a + b;
    }

    public int sub(int a, int b) {
        return a - b;
    }
}
